import { DirectoryNode } from './types';

export interface FlatFileNode {
  path: string;
  name: string;
  type: 'file' | 'directory';
  level: number;
  description?: string;
  isOpen?: boolean;
}

/**
 * Traverses a recursive directory tree inside a blueprint and returns a flat representation 
 * of nodes with correct relative paths, nested levels, and files.
 */
export function flattenDirectoryTree(
  tree: Record<string, any>,
  parentPath = '',
  level = 0
): FlatFileNode[] {
  let nodes: FlatFileNode[] = [];

  // Sort directories first, then files
  const entries = Object.entries(tree).sort((a, b) => {
    const typeA = a[1].type || 'file';
    const typeB = b[1].type || 'file';
    if (typeA === 'directory' && typeB === 'file') return -1;
    if (typeA === 'file' && typeB === 'directory') return 1;
    return a[0].localeCompare(b[0]);
  });

  for (const [name, data] of entries) {
    const currentPath = parentPath ? `${parentPath}/${name}` : name;
    const isDir = data.type === 'directory';

    nodes.push({
      path: currentPath,
      name,
      type: isDir ? 'directory' : 'file',
      level,
      description: data.description,
      isOpen: true,
    });

    if (isDir && data.children) {
      nodes = [...nodes, ...flattenDirectoryTree(data.children, currentPath, level + 1)];
    }
  }

  return nodes;
}

/**
 * Inspects a blueprint, ensuring its filesContent matches what's listed in directory tree.
 * Re-maps files that were generated by setup scripts or setup_sh.
 */
export function sanitizeBlueprintFiles(blueprint: any): Record<string, string> {
  const files: Record<string, string> = { ...(blueprint.filesContent || {}) };

  // Fallback to extract content from setup_sh if present and not already mapped
  if (blueprint.setup_sh && blueprint.setup_sh.content && !files[blueprint.setup_sh.scriptName || 'setup.sh']) {
    files[blueprint.setup_sh.scriptName || 'setup.sh'] = blueprint.setup_sh.content;
  }

  // Ensure standard files are filled if empty
  if (Object.keys(files).length === 0) {
    files['README.md'] = `# ${blueprint.projectName || 'Projeto'}\n\n${blueprint.description || ''}\n\n## Objetivo\n${blueprint.objective || ''}`;
  }

  return files;
}

/**
 * Format filesizes for display
 */
export function formatSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
}
